server-name=Blaze Bedrock
gamemode=survival
force-gamemode=false
difficulty=normal
allow-cheats=true
max-players=10
online-mode=false
allow-list=false
server-port=2519
server-udp-ports=46.232.234.21:2519:2519
server-portv6=19133
enable-lan-visibility=true
view-distance=6
tick-distance=4
player-idle-timeout=30
max-threads=4
level-name=Bedrock level
level-seed=7644899971978172129
default-player-permission-level=member
texturepack-required=true
content-log-file-enabled=false
content-log-console-output-enabled=false
content-log-level=error
compression-threshold=256
compression-algorithm=zlib
client-side-chunk-generation-enabled=true
block-network-ids-are-hashes=true
disable-persona=true
disable-custom-skins=false
server-authoritative-movement-strict=false
player-position-acceptance-threshold=1.5
chat-restriction=None
enable-query=true
